### ISSUE TITLE
Virtual Keys UI isn't showing all fields and won't work

### ISSUE THREAD

**Issue by MasterDevwi** [kcsoft/virtual-keys#6]
It's been a few months since I've used virtual keys, but I have a guest staying with me so I wanted to set one up. Unfortunately, when I visit the page to create a new virtual key most of the UI doesn't appear. I can see the option to select a user, but not a custom username or timeout. Because of this, I'm unable to create a virtual key.

![image](https://github.com/kcsoft/virtual-keys/assets/5544757/b6008685-5421-4d1f-84e8-69d4fdc3f045)

I recently updated to 2024.5.0, but it's possible this was introduced in an earlier update since I haven't used virtual keys in a bit. To ensure the issue wasn't on my end, I've tried reinstalling virtual keys and double checking configuration.yaml. Everything appears to be in order and matches the instructions on GitHub.

Any idea how to fix this @kcsoft? Thanks in advance! I love this add-on.

**Comment by kcsoft** [comment]
Try reinstalling virtual-keys, make sure to clear the cache. 
There were some issues related to this but they are now fixed, it is working fine with HA 05.2024

**Comment by MasterDevwi** [comment]
I’m still unable to get it to work, even after reinstalling and clearing the cache in both the browser and the app. Any ideas?

**Comment by kcsoft** [comment]
I still suspect that somehow you are not using the latest version.
Can you please try this with Chrome (open Developer Tools) or similar browser
![image](https://github.com/kcsoft/virtual-keys/assets/176441/4fb8786f-bc02-4dab-8664-4f57681afa81)

**Comment by MasterDevwi** [comment]
Thanks! You're right, I'm definitely on the old version:

![image](https://github.com/kcsoft/virtual-keys/assets/5544757/0411d561-f623-4f79-a33b-c711ceb3bd1d)

Strangely though, I can't seem to get the new version to load. I've tried redownloading via HACS, completely uninstalling and reinstalling, clearing my browser cache, and even using multiple devices. Nothing seems to work. The manifest.json in custom_components/virtual_keys says the version number is 0.1.0, and I did a diff against \_\_init\_\_.py on GitHub and they seem to be identical. So it seems like I have the latest version, but it's just not loading properly?

**Comment by kcsoft** [comment]
I updated `manifest.json` to `v0.2.0` (should have done).

Also you can try manually deleting `<HA folder> -> www -> community -> virtual-keys`

**Comment by MasterDevwi** [comment]
Thank you! That fixed it. In the process of doing the reinstall this time, I realized that I may not have reinstalled virtual-keys as both a frontend and integration repo before. 🤦🏻‍♂️ It's possible (and in hindsight quite likely) that that contributed to the issue too. I guess the built in updater for HACS doesn't know how to handle this kind of situation. I suspect it updated the integration but couldn't update the frontend and that's why it stopped working.

Anyway, thank you so much for your help!
